# Generated by Django 3.0.6 on 2020-05-16 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200516_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='u',
        ),
    ]
