# Generated by Django 3.0.6 on 2020-05-16 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_people_u'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.People'),
        ),
    ]
