# Generated by Django 3.0.6 on 2020-05-16 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200516_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mainapp.People'),
        ),
    ]
