# Generated by Django 3.0.6 on 2020-05-20 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20200520_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='marks', to='mainapp.Subjects'),
        ),
    ]
