# Generated by Django 3.0.6 on 2020-05-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20200520_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
