# Generated by Django 3.0.6 on 2020-05-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20200520_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='year',
        ),
    ]
