# Generated by Django 3.0.6 on 2020-05-20 16:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_marks_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 16, 13, 35, 810466, tzinfo=utc)),
        ),
    ]
