# Generated by Django 3.0.6 on 2020-05-20 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20200520_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
