# Generated by Django 3.0.6 on 2020-05-20 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0021_auto_20200520_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='people',
            name='u',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='man', to=settings.AUTH_USER_MODEL),
        ),
    ]
