# Generated by Django 3.0.6 on 2020-05-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20200520_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
